// Ícone de cada comércio. Primeiro pelo tipo exato do Google
// ("hamburger_restaurant" → hambúrguer), depois por pedaços do tipo
// ("..._restaurant" → talheres) e, sem tipo, pelo ramo do Pagefy.
import {
  Apple,
  Bath,
  Bed,
  Beef,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Cake,
  Calculator,
  Camera,
  Candy,
  Car,
  Coffee,
  Croissant,
  Donut,
  Drumstick,
  Dumbbell,
  Fish,
  Flower2,
  Footprints,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Hamburger,
  Hammer,
  HeartPulse,
  House,
  IceCreamCone,
  KeyRound,
  Laptop,
  Martini,
  Megaphone,
  Music,
  Package,
  Paintbrush,
  PartyPopper,
  PawPrint,
  PenTool,
  Pill,
  Pizza,
  Printer,
  Sandwich,
  Scale,
  Scissors,
  Shield,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Soup,
  Sparkles,
  Stethoscope,
  Store,
  Truck,
  UtensilsCrossed,
  WashingMachine,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const BY_TYPE: Record<string, LucideIcon> = {
  // Alimentação
  bakery: Croissant,
  cafe: Coffee,
  coffee_shop: Coffee,
  cafeteria: Coffee,
  tea_house: Coffee,
  pizza_restaurant: Pizza,
  hamburger_restaurant: Hamburger,
  fast_food_restaurant: Hamburger,
  sandwich_shop: Sandwich,
  deli: Sandwich,
  ice_cream_shop: IceCreamCone,
  acai_shop: IceCreamCone,
  dessert_shop: Cake,
  confectionery: Cake,
  donut_shop: Donut,
  candy_store: Candy,
  chocolate_shop: Candy,
  seafood_restaurant: Fish,
  sushi_restaurant: Fish,
  japanese_restaurant: Fish,
  steak_house: Beef,
  barbecue_restaurant: Beef,
  butcher_shop: Beef,
  chicken_restaurant: Drumstick,
  meal_takeaway: Soup,
  meal_delivery: Soup,
  // Bares
  bar: Beer,
  pub: Beer,
  bar_and_grill: Beer,
  wine_bar: Wine,
  night_club: Martini,
  karaoke: Music,
  // Beleza
  barber_shop: Scissors,
  hair_salon: Scissors,
  hair_care: Scissors,
  beauty_salon: Sparkles,
  nail_salon: Sparkles,
  makeup_artist: Sparkles,
  spa: Bath,
  sauna: Bath,
  massage: HeartPulse,
  massage_spa: HeartPulse,
  tattoo_shop: PenTool,
  body_art_service: PenTool,
  // Saúde
  pet_store: PawPrint,
  veterinary_care: PawPrint,
  pet_care: PawPrint,
  pharmacy: Pill,
  drugstore: Pill,
  optician: Glasses,
  doctor: Stethoscope,
  dentist: Stethoscope,
  dental_clinic: Stethoscope,
  medical_clinic: Stethoscope,
  physiotherapist: HeartPulse,
  // Automotivo
  car_repair: Wrench,
  car_wash: Car,
  auto_parts_store: Car,
  motorcycle_repair: Wrench,
  motorcycle_dealer: Bike,
  bicycle_store: Bike,
  // Corpo
  gym: Dumbbell,
  fitness_center: Dumbbell,
  yoga_studio: HeartPulse,
  // Casa
  hardware_store: Hammer,
  home_improvement_store: Hammer,
  general_contractor: Hammer,
  electrician: Zap,
  plumber: Wrench,
  painter: Paintbrush,
  locksmith: KeyRound,
  furniture_store: Sofa,
  home_goods_store: Sofa,
  interior_designer: Sofa,
  // Comércio
  clothing_store: Shirt,
  shoe_store: Footprints,
  jewelry_store: Gem,
  supermarket: ShoppingCart,
  grocery_store: ShoppingBasket,
  convenience_store: ShoppingBasket,
  market: Apple,
  farmers_market: Apple,
  electronics_store: Laptop,
  computer_store: Laptop,
  cell_phone_store: Smartphone,
  florist: Flower2,
  gift_shop: Gift,
  toy_store: Gift,
  book_store: BookOpen,
  // Serviços
  lawyer: Scale,
  accounting: Calculator,
  real_estate_agency: House,
  insurance_agency: Shield,
  print_shop: Printer,
  advertising_agency: Megaphone,
  marketing_agency: Megaphone,
  // Educação e eventos
  school: GraduationCap,
  preschool: GraduationCap,
  driving_school: Car,
  event_venue: PartyPopper,
  wedding_venue: PartyPopper,
  banquet_hall: PartyPopper,
  photographer: Camera,
  // Outros
  laundry: WashingMachine,
  dry_cleaner: WashingMachine,
  tailor: Scissors,
  moving_company: Truck,
  storage: Package,
  courier_service: Package,
  // Fora dos ramos, mas o Google devolve às vezes
  lodging: Bed,
  hotel: Bed,
  motel: Bed,
  hostel: Bed,
  inn: Bed,
  guest_house: Bed,
};

// Tipo sem entrada própria: pelo pedaço do nome.
const BY_SUFFIX: Array<[RegExp, LucideIcon]> = [
  [/_restaurant$/, UtensilsCrossed],
  [/_school$/, GraduationCap],
  [/_(clinic|center)$/, Stethoscope],
  [/_store$|_shop$/, Store],
  [/_agency$|_office$/, Briefcase],
];

const BY_CATEGORY: Record<string, LucideIcon> = {
  restaurantes: UtensilsCrossed,
  bares: Beer,
  saloes: Sparkles,
  barbearia: Scissors,
  estetica: HeartPulse,
  tatuagem: PenTool,
  clinicas: Stethoscope,
  pet: PawPrint,
  farmacias: Pill,
  oficina: Wrench,
  motos: Bike,
  academias: Dumbbell,
  material: Hammer,
  reformas: Paintbrush,
  moveis: Sofa,
  roupas: Shirt,
  mercados: ShoppingCart,
  eletronicos: Smartphone,
  presentes: Gift,
  advocacia: Scale,
  imobiliarias: Building2,
  seguros: Shield,
  graficas: Printer,
  escolas: GraduationCap,
  festas: PartyPopper,
  lavanderias: WashingMachine,
  transporte: Truck,
};

export function businessIcon(business: { type?: string | null; category: { id: string } }): LucideIcon {
  const type = business.type;
  if (type) {
    const exact = BY_TYPE[type];
    if (exact) return exact;
    const partial = BY_SUFFIX.find(([pattern]) => pattern.test(type));
    if (partial) return partial[1];
  }
  return BY_CATEGORY[business.category.id] ?? Store;
}
